# Generated by Django 3.0.4 on 2020-03-20 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afectado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nac', models.DateField()),
                ('rut', models.IntegerField()),
                ('telefono1', models.IntegerField()),
                ('telefono2', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='aseguradoras', to='server.Afectado')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento_plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admisibilidad_if', models.IntegerField()),
                ('admisibilidad_ip', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grupo_permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default=True)),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='server.Afectado')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_problema', models.DateField()),
                ('fecha_res_recl_aprestador', models.DateField()),
                ('fecha_res_pres', models.DateField()),
                ('fecha_notificacion', models.DateField()),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestadores', to='server.Afectado')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reclamante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del Reclamante', max_length=50, null=True)),
                ('apellido_paterno', models.CharField(blank=True, help_text='Apellido Paterno del Reclamante', max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, help_text='Apellido Materno del Reclamante', max_length=50, null=True)),
                ('fecha_nac', models.DateField(help_text='Fecha de Nacimiento del Reclamante')),
                ('nacionalidad', models.IntegerField(help_text='Nacionalidad del Reclamante')),
                ('telefono1', models.IntegerField(help_text='Telefono de Reclamante')),
                ('telefono2', models.IntegerField(help_text='Telefono Segundario de Reclamante')),
                ('rut', models.IntegerField(help_text='Rut del Reclamante')),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamantes', to='server.Afectado')),
                ('documento', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamantes', to='server.Documento')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_presentacion', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('materia', models.IntegerField()),
                ('sub_materia1', models.IntegerField()),
                ('sub_materia2', models.IntegerField()),
                ('sub_materia3', models.IntegerField()),
                ('descripcion_problema', models.TextField(default=True)),
                ('solucion_esperada', models.TextField(default=True)),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='server.Afectado')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='server.Reclamante')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_reclamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario_grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admisibilidad_if', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del Usuario', max_length=30, null=True)),
                ('apellido_paterno', models.CharField(blank=True, help_text='Apellido Paterno del Usuario', max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, help_text='Apellido Materno del Usuario', max_length=50, null=True)),
                ('rut', models.IntegerField(help_text='Rut del Usuario')),
                ('direccion', models.CharField(blank=True, help_text='Direccion del Usuario', max_length=50, null=True)),
                ('telefono', models.IntegerField(help_text='Numero Telefonico del Usuario')),
                ('correo_electronico', models.EmailField(help_text='Correo Electronico del Usuario', max_length=50)),
                ('fecha_nac', models.DateField(help_text='Fecha de Nacimiento del Usuario')),
                ('comuna', models.CharField(blank=True, help_text='Comuna del Usuario', max_length=50, null=True)),
                ('rol', models.IntegerField(default=True)),
                ('grupo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='server.Grupo')),
                ('grupo_permiso', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='server.Grupo_permiso')),
                ('tipo_usuario', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='server.Tipo_usuario')),
                ('usuario_grupo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='server.Usuario_grupo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Usuario', verbose_name='Usuario')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_prestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publico', models.BooleanField()),
                ('privado', models.BooleanField()),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_prestadores', to='server.Afectado')),
                ('prestador', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_prestadores', to='server.Prestador')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_prestadores', to='server.Reclamante')),
                ('reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_prestadores', to='server.Reclamo')),
                ('tipo_reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_prestadores', to='server.Tipo_reclamo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_aseguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aseguradora', models.CharField(blank=True, max_length=50, null=True)),
                ('rut_aseguradora', models.IntegerField()),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.IntegerField()),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_aseguradoras', to='server.Afectado')),
                ('aseguradora', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_aseguradoras', to='server.Aseguradora')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_aseguradoras', to='server.Reclamante')),
                ('reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_aseguradoras', to='server.Reclamo')),
                ('tipo_reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_aseguradoras', to='server.Tipo_reclamo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Submateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion1', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion2', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion3', models.CharField(blank=True, max_length=50, null=True)),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='submaterias', to='server.Afectado')),
                ('materia', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='submaterias', to='server.Materia')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='submaterias', to='server.Reclamante')),
                ('reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='submaterias', to='server.Reclamo')),
                ('tipo_reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='submaterias', to='server.Tipo_reclamo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Opcional')], max_length=1)),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='sexos', to='server.Afectado')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='sexos', to='server.Reclamante')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reparo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('cursar_reclamo', models.CharField(blank=True, max_length=50, null=True)),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reparos', to='server.Afectado')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reparos', to='server.Reclamante')),
                ('reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reparos', to='server.Reclamo')),
                ('tipo_reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reparos', to='server.Tipo_reclamo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='server.Afectado')),
                ('aseguradora', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='server.Aseguradora')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='server.Reclamante')),
                ('reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='server.Reclamo')),
                ('tipo_reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='server.Tipo_reclamo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reclamo_reclamante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos_reclamantes', to='server.Afectado')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos_reclamantes', to='server.Reclamante')),
                ('reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos_reclamantes', to='server.Reclamo')),
                ('tipo_reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos_reclamantes', to='server.Tipo_reclamo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='reclamo',
            name='tipo_reclamo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='server.Tipo_reclamo'),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='server.Afectado')),
                ('aseguradora', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='server.Aseguradora')),
                ('comuna', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='server.Comuna')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='server.Reclamante')),
                ('reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='server.Reclamo')),
                ('region', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='server.Region')),
                ('tipo_reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='server.Tipo_reclamo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(blank=True, max_length=50, null=True)),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesiones', to='server.Reclamante')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='prestador',
            name='reclamante',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestadores', to='server.Reclamante'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='reclamo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestadores', to='server.Reclamo'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='tipo_reclamo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestadores', to='server.Tipo_reclamo'),
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='nacionalidades', to='server.Afectado')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='reclamante',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='server.Reclamante'),
        ),
        migrations.AddField(
            model_name='materia',
            name='reclamo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='server.Reclamo'),
        ),
        migrations.AddField(
            model_name='materia',
            name='tipo_reclamo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='server.Tipo_reclamo'),
        ),
        migrations.CreateModel(
            name='Intendencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='intendencias', to='server.Afectado')),
                ('materia', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='intendencias', to='server.Materia')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='intendencias', to='server.Reclamante')),
                ('reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='intendencias', to='server.Reclamo')),
                ('submateria', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='intendencias', to='server.Submateria')),
                ('tipo_reclamo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='intendencias', to='server.Tipo_reclamo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='server.Reclamante')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='grupo_permiso',
            name='usuario_grupo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_permisos', to='server.Usuario_grupo'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='grupo_permiso',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='server.Grupo_permiso'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuario_grupo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='server.Usuario_grupo'),
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mujer', models.IntegerField(default=True)),
                ('hombre', models.IntegerField(default=True)),
                ('persona_trans', models.IntegerField(default=True)),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='generos', to='server.Afectado')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='generos', to='server.Reclamante')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estado_civil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soltero', models.BooleanField()),
                ('casado', models.BooleanField()),
                ('viudo', models.BooleanField()),
                ('separado', models.BooleanField()),
                ('divorciado', models.BooleanField()),
                ('union_libre', models.BooleanField()),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='server.Afectado')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='server.Reclamante')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='documento_plantilla',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='server.Documento_plantilla'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('pasaje', models.CharField(blank=True, max_length=50, null=True)),
                ('avenida', models.CharField(blank=True, max_length=50, null=True)),
                ('afectado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='server.Afectado')),
                ('reclamante', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='server.Reclamante')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='aseguradora',
            name='reclamante',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='aseguradoras', to='server.Reclamante'),
        ),
        migrations.AddField(
            model_name='aseguradora',
            name='reclamo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='aseguradoras', to='server.Reclamo'),
        ),
        migrations.AddField(
            model_name='aseguradora',
            name='tipo_reclamo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='aseguradoras', to='server.Tipo_reclamo'),
        ),
        migrations.AddField(
            model_name='afectado',
            name='comuna',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='afectados', to='server.Comuna'),
        ),
    ]
