# Generated by Django 3.0.5 on 2020-04-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0065_auto_20200420_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono1', models.IntegerField(blank=True, null=True)),
                ('rut', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
