# Generated by Django 2.2.6 on 2020-04-20 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0065_auto_20200420_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_camunda',
            name='user',
        ),
        migrations.RemoveField(
            model_name='datos_process_definition',
            name='proceso',
        ),
        migrations.CreateModel(
            name='Process_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_plano', models.CharField(max_length=60, null=True)),
                ('definitionId', models.CharField(max_length=60, null=True)),
                ('businessKey', models.CharField(max_length=60, null=True)),
                ('caseInstanceId', models.CharField(max_length=60, null=True)),
                ('ended', models.BooleanField(default=False)),
                ('suspended', models.BooleanField(default=False)),
                ('tenantId', models.CharField(max_length=60, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datos_process_definition',
            name='instancia_proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instancia_proceso', to='server.Process_Instance'),
        ),
    ]
