# Generated by Django 3.0.5 on 2020-04-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0068_reclamo_representante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamo',
            name='representante',
        ),
    ]
