# Generated by Django 3.0.5 on 2020-04-21 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0070_reclamo_representante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='telefono1',
        ),
        migrations.AddField(
            model_name='representante',
            name='descripcion',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='representante',
            name='genero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Genero'),
        ),
    ]
