# Generated by Django 3.0.5 on 2020-04-21 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0071_auto_20200421_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='representante',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='server.Representante'),
        ),
    ]
