# Generated by Django 3.0.5 on 2020-04-21 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0072_auto_20200421_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='hombre',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='mujer',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='persona_trans',
        ),
        migrations.AddField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='representante',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='server.Representante'),
        ),
    ]
