# Generated by Django 3.0.5 on 2020-04-21 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0075_auto_20200421_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='generorepresentante',
            field=models.OneToOneField(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='server.GeneroRepresentante'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='representante',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='server.Representante'),
        ),
    ]
