# Generated by Django 3.0.5 on 2020-04-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0076_auto_20200421_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamante',
            name='digitoverificador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
