# Generated by Django 3.0.5 on 2020-04-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0078_auto_20200421_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='tipo_beneficiario',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
