# Generated by Django 3.0.5 on 2020-04-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0079_auto_20200421_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
