# Generated by Django 3.0.5 on 2020-04-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0080_representante_fecha_nac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamo',
            name='copia_ced_rep',
        ),
        migrations.AddField(
            model_name='representante',
            name='copia_ced_rep',
            field=models.FileField(blank=True, null=True, upload_to='Escritorio/'),
        ),
    ]
