# Generated by Django 3.0.5 on 2020-04-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0082_reclamo_complaint_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
