# Generated by Django 3.0.5 on 2020-04-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0085_reclamo_hasta_uno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamo',
            old_name='hasta_uno',
            new_name='hasta_dos',
        ),
    ]
