# Generated by Django 3.0.5 on 2020-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0086_auto_20200421_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
