# Generated by Django 3.0.5 on 2020-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0087_representante_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='desde_uno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
