# Generated by Django 3.0.5 on 2020-04-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0093_auto_20200421_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
