# Generated by Django 3.0.5 on 2020-04-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0094_representante_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='triage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
