# Generated by Django 3.0.5 on 2020-04-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0095_reclamo_triage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='hospitalizacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
