# Generated by Django 3.0.5 on 2020-04-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0097_auto_20200421_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante',
            name='pdf_cedula',
        ),
        migrations.AddField(
            model_name='reclamante',
            name='pdf_cedula',
            field=models.FileField(blank=True, null=True, upload_to='Escritorio/'),
        ),
    ]
