# Generated by Django 3.0.5 on 2020-04-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0098_auto_20200421_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='telefono1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='representante',
            name='telefono2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
