# Generated by Django 3.0.5 on 2020-04-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0102_reclamo_sexorepresentante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamo',
            name='sexorepresentante',
        ),
        migrations.DeleteModel(
            name='SexoRepresentante',
        ),
    ]
