# Generated by Django 3.0.5 on 2020-04-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0105_reclamo_sexorepresentante'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='lugar_tres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
