# Generated by Django 3.0.5 on 2020-04-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0106_reclamo_lugar_tres'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroReclamante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
