# Generated by Django 3.0.5 on 2020-04-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0110_reclamo_nacionalidadrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='region',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='server.Region'),
        ),
    ]
