# Generated by Django 3.0.5 on 2020-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0111_representante_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='afectado',
            name='digitoverificador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
