# Generated by Django 3.0.5 on 2020-04-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0112_afectado_digitoverificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='direccion',
            field=models.OneToOneField(blank=True, default=None, help_text='Direccion de Afectado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='server.Direccion'),
        ),
    ]
