# Generated by Django 3.0.5 on 2020-04-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0113_representante_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='hasta_uno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
