# Generated by Django 3.0.5 on 2020-04-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0116_reclamo_comunarep'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='comunarep',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='server.ComunaRepresentante'),
        ),
    ]
