# Generated by Django 3.0.5 on 2020-04-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0118_remove_reclamo_comunarep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante',
            name='comunarep',
        ),
    ]
