# Generated by Django 3.0.5 on 2020-04-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0124_auto_20200421_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='desde_tres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
