# Generated by Django 3.0.5 on 2020-04-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0125_reclamo_desde_tres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamo',
            old_name='descripcion_problema',
            new_name='desc_problema',
        ),
    ]
