# Generated by Django 3.0.5 on 2020-04-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0126_auto_20200421_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='tipo_rep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
