# Generated by Django 3.0.5 on 2020-04-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0128_reclamo_hasta_tres'),
    ]

    operations = [
        migrations.AddField(
            model_name='afectado',
            name='tipo_pac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
