# Generated by Django 3.0.5 on 2020-04-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0129_afectado_tipo_pac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamo',
            name='tipo_rep',
        ),
    ]
