# Generated by Django 3.0.5 on 2020-04-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0130_remove_reclamo_tipo_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='lugar_dos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
