# Generated by Django 2.2.6 on 2020-04-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0137_reclamo_categoria_clasificador'),
        ('server', '0066_auto_20200420_2205'),
    ]

    operations = [
    ]
