# Generated by Django 2.2.6 on 2020-04-23 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0139_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
